/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
           
import Controller.ControllerDepartamento;
import Controller.ControllerFornecedor;
import Controller.ControllerProduto; 
import Model.ModelDepartamento;
import Model.ModelFornecedor;
import Model.ModelProduto;
import Util.Formatador;
import java.awt.Color;
import java.awt.Component;
import java.awt.Toolkit;
import java.text.DecimalFormat;  
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 * 
 * @author Monet
 */
public class ViewProduto2 extends javax.swing.JFrame {
     ModelProduto modelProduto = new ModelProduto();
     ControllerProduto controllerProduto = new ControllerProduto();
     ArrayList<ModelProduto> listaProduto = new ArrayList<>();
     
     ModelDepartamento modelDepartamento = new ModelDepartamento();
     ControllerDepartamento controllerDepartamento = new ControllerDepartamento();
     ArrayList<ModelDepartamento> listaDepartamento = new ArrayList<>();
     
     ModelFornecedor modelFornecedor = new ModelFornecedor();
     ControllerFornecedor controllerFornecedor = new ControllerFornecedor();
     ArrayList<ModelFornecedor> listaFornecedor = new ArrayList<>();
      Formatador formatador = new Formatador(); 
      DecimalFormat df = new DecimalFormat("#.00");
     String botao;
     String CLASS;
    /**
     * Creates new form ViewProduto
     */
    public ViewProduto2() {
        initComponents();
        setIcon();
        tfNome.requestFocus();
        listandoFornecedor();
        listandoDepartamento(); 
        listandoProdutos();
        tfEstoque.setText("0"); 
        corLinha();
    }
    
    
 
    
    
    private void limpandoCampos(){
    tfAtributo.setText("");
    tfBarras.setText("");
    tfEstoque.setText("0");
    tfId.setText("");
    tfIndAtributo.setText("");
    tfNcm.setText("");
    tfNome.setText("");
    tfValidade.setText("");
    jcbDepartamento.setSelectedItem("DEPARTAMENTO");
        jcbFornecedor.setSelectedItem("FORNECEDOR");

    }
    private void listandoFornecedor(){
    listaFornecedor = controllerFornecedor.listaModelController();
    jcbFornecedor.removeAllItems();
        for (int i = 0; i < listaFornecedor.size(); i++) {
        jcbFornecedor.addItem(listaFornecedor.get(i).getNome());
        }
    }
    private void listandoDepartamento(){
    listaDepartamento = controllerDepartamento.listaModelController();
    jcbDepartamento.removeAllItems();
        for (int i = 0; i < listaDepartamento.size(); i++) {
            jcbDepartamento.addItem(listaDepartamento.get(i).getNome());
        }
    }
    private void listandoProdutos(){
        listaProduto = controllerProduto.listaModelUsuarioController();
        DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
        modelo.setNumRows(0);
        for (int i = 0; i < listaProduto.size(); i++) {
        modelo.addRow(new Object[]{
        listaProduto.get(i).getId(),
        listaProduto.get(i).getNome(),
        listaProduto.get(i).getEstoque(),
        listaProduto.get(i).getCod_barras(),
        listaProduto.get(i).getDepartamento(),
        listaProduto.get(i).getAtributo(),
        listaProduto.get(i).getInd_atributo(),
        listaProduto.get(i).getNcm(),
        listaProduto.get(i).getFornecedor(),
        listaProduto.get(i).getValidade(),
        df.format(listaProduto.get(i).getPreco_custo()),
        df.format(listaProduto.get(i).getPreco_venda())
        
        });
        }
        corLinha();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */ 
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfEstoque = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfBarras = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jcbDepartamento = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        tfValidade = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfAtributo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jcbFornecedor = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        tfIndAtributo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tfNcm = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tfCusto = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tfVenda = new javax.swing.JTextField();
        botaoInserirQuantia = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnAtualizar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        tfPesquisa = new javax.swing.JTextField();
        btnInserir = new javax.swing.JButton();
        tfBuscaPorCodBarras = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CADASTRO DE PRODUTOS (ESTIVAS)");
        setResizable(false);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NOME", "ESTOQUE", "COD.BARRAS", "DEPARTAMENTO", "ATRIBUTO", "IND.ATRIBUTO", "NCM", "FORNECEDOR", "VALIDADE", "PRE.CUSTO", "PRE.VENDA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);
        if (tabela.getColumnModel().getColumnCount() > 0) {
            tabela.getColumnModel().getColumn(0).setResizable(false);
            tabela.getColumnModel().getColumn(2).setResizable(false);
            tabela.getColumnModel().getColumn(3).setResizable(false);
            tabela.getColumnModel().getColumn(4).setResizable(false);
            tabela.getColumnModel().getColumn(5).setResizable(false);
            tabela.getColumnModel().getColumn(6).setResizable(false);
            tabela.getColumnModel().getColumn(7).setResizable(false);
            tabela.getColumnModel().getColumn(8).setResizable(false);
            tabela.getColumnModel().getColumn(9).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setText("ID:");

        tfId.setEditable(false);

        jLabel2.setText("NOME:");

        tfNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfNomeKeyReleased(evt);
            }
        });

        jLabel3.setText("ESTOQUE:");

        tfEstoque.setEditable(false);
        tfEstoque.setBackground(new java.awt.Color(33, 48, 64));
        tfEstoque.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setText("COD.BARRAS:");

        tfBarras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBarrasActionPerformed(evt);
            }
        });

        jLabel5.setText("DEPARTAMENTO:");

        jcbDepartamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("VALIDADE:");

        tfValidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfValidadeActionPerformed(evt);
            }
        });

        jLabel7.setText("ATRIBUTO:");

        jLabel8.setText("FORNECEDOR:");

        jcbFornecedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel9.setText("IND.ATRIBUTO:");

        jLabel10.setText("NCM:");

        jLabel12.setText("PREÇO CUSTO:");

        tfCusto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfCustoFocusLost(evt);
            }
        });
        tfCusto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfCustoKeyReleased(evt);
            }
        });

        jLabel13.setText("PREÇO VENDA:");

        tfVenda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfVendaFocusLost(evt);
            }
        });

        botaoInserirQuantia.setText("INSERIR QUANTIDADE");
        botaoInserirQuantia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoInserirQuantiaActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setText("*");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 0, 0));
        jLabel17.setText("*");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel2))
                        .addComponent(jLabel5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfBarras))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfValidade)
                                    .addComponent(jcbFornecedor, 0, 160, Short.MAX_VALUE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfIndAtributo, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel7))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNcm, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfAtributo, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tfCusto, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addGap(10, 10, 10)
                        .addComponent(tfVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botaoInserirQuantia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(tfEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(tfBarras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(tfAtributo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jcbFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(tfValidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfIndAtributo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(jLabel10)
                        .addComponent(tfNcm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(tfVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoInserirQuantia)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        btnAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Atualizar.png"))); // NOI18N
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnEditar.setText("EDITAR");
        btnEditar.setEnabled(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setText("EXCLUIR");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnCadastrar.setText("CADASTRAR");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        jLabel11.setText("Pesquisar:");

        tfPesquisa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfPesquisaFocusLost(evt);
            }
        });
        tfPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPesquisaActionPerformed(evt);
            }
        });
        tfPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfPesquisaKeyReleased(evt);
            }
        });

        btnInserir.setText("INSERIR");
        btnInserir.setEnabled(false);
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        tfBuscaPorCodBarras.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfBuscaPorCodBarrasFocusLost(evt);
            }
        });
        tfBuscaPorCodBarras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfBuscaPorCodBarrasKeyReleased(evt);
            }
        });

        jLabel14.setText("Buscar pelo código de barras:");

        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setText("As caixas de textos marcadas (*) só irão receber valores numéricos!");

        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnInserir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfBuscaPorCodBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel15))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfBuscaPorCodBarras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtualizar)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluir)
                    .addComponent(btnCadastrar)
                    .addComponent(btnInserir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfBarrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBarrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBarrasActionPerformed

    private void tfValidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfValidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfValidadeActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
    if(tfNome.getText().equals("") || tfAtributo.getText().equals("") 
    || jcbDepartamento.getSelectedItem().equals("DEPARTAMENTO") || jcbFornecedor.getSelectedItem().equals("FORNECEDOR") 
    || tfBarras.getText().equals("") 
    || tfEstoque.getText().equals("")  || tfIndAtributo.getText().equals("") || tfNcm.getText().equals("") || tfValidade.getText().equals("")){
    JOptionPane.showMessageDialog(this, "OPA!!!.", "PRODUTO", 0,
    new ImageIcon(getClass().getResource("/imagem/OPA.png"))); 
    JOptionPane.showMessageDialog(this, "Todos os campos são obrigatórios!!!.", "PRODUTO", 0,
    new ImageIcon(getClass().getResource("/imagem/ATENCAO.png"))); 
    JOptionPane.showMessageDialog(this, "NÃO IDENTIFIQUEI OS DADOS!.", "PRODUTO", 0,
    new ImageIcon(getClass().getResource("/imagem/informe produto.png")));
    }else{  
        try {
            
        
    modelProduto.setNome(tfNome.getText());
    modelProduto.setAtributo(tfAtributo.getText());
    modelProduto.setCod_barras(tfBarras.getText());
    modelProduto.setDepartamento(jcbDepartamento.getSelectedItem()+"");
    modelProduto.setEstoque(Integer.parseInt(tfEstoque.getText()));
    modelProduto.setFornecedor(jcbFornecedor.getSelectedItem()+"");
    modelProduto.setInd_atributo(tfIndAtributo.getText());
    modelProduto.setNcm(tfNcm.getText());
    modelProduto.setValidade(tfValidade.getText()); 
    
    modelProduto.setPreco_venda(Double.parseDouble(tfVenda.getText()));
    modelProduto.setPreco_custo(Double.parseDouble(tfCusto.getText()));
    modelProduto.setValidade(tfValidade.getText()); 
    if(controllerProduto.salvarController(modelProduto)>0){
    JOptionPane.showMessageDialog(this, "Salvo com sucesso!!!.", "PRODUTO", 0,
    new ImageIcon(getClass().getResource("/imagem/CERTO.png"))); 
    limpandoCampos();
    listandoProdutos();
    tfNome.requestFocus();
    }
    } catch (Exception e) {
       JOptionPane.showMessageDialog(this, "As caixas de textos que que contém (*) só pode informar números."); 
        }
    }
    
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
    btnCadastrar.setEnabled(false);
    btnEditar.setEnabled(true);
    btnInserir.setEnabled(true);
    btnExcluir.setEnabled(true);
    try {
        int linha = tabela.getSelectedRow(); 
    String cod = (String) tabela.getValueAt(linha, 0);
    modelProduto = controllerProduto.retornarController(Integer.parseInt(cod));
    tfId.setText(String.valueOf(modelProduto.getId()));
    tfNome.setText(modelProduto.getNome());
    tfBarras.setText(modelProduto.getCod_barras());
    tfEstoque.setText(modelProduto.getEstoque()+"");
    tfValidade.setText(modelProduto.getValidade());
    jcbDepartamento.setSelectedItem(modelProduto.getDepartamento());
    jcbFornecedor.setSelectedItem(modelProduto.getFornecedor());
    tfAtributo.setText(modelProduto.getAtributo());
    tfIndAtributo.setText(modelProduto.getInd_atributo());
    tfNcm.setText(modelProduto.getNcm());
     tfCusto.setText(modelProduto.getPreco_custo()+"");
    tfVenda.setText(modelProduto.getPreco_venda()+"");
    } catch (Exception e) { 
    JOptionPane.showMessageDialog(null, "PRECIONE O BOTÃO (INSERIR)!!!");
    } 
       
    }//GEN-LAST:event_tabelaMouseClicked

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
    if(tfId.getText().equals("")){
    JOptionPane.showMessageDialog(this, "OPA!!!.", "CLIENTE", 0,
    new ImageIcon(getClass().getResource("/imagem/OPA.png"))); 
    JOptionPane.showMessageDialog(this, "INFORME UMA LINHA NA TABELA.", "CLIENTE", 0,
    new ImageIcon(getClass().getResource("/imagem/ATENCAO.png"))); 
    JOptionPane.showMessageDialog(this, "NÃO IDENTIFIQUEI OS DADOS.", "CLIENTE", 0,
    new ImageIcon(getClass().getResource("/imagem/informe produto.png"))); 
    }else{
         
    modelProduto.setNome(tfNome.getText());
    modelProduto.setAtributo(tfAtributo.getText());
    modelProduto.setCod_barras(tfBarras.getText());
    modelProduto.setDepartamento(jcbDepartamento.getSelectedItem()+"");
    modelProduto.setEstoque(Integer.parseInt(tfEstoque.getText()));
    modelProduto.setFornecedor(jcbFornecedor.getSelectedItem()+"");
    modelProduto.setInd_atributo(tfIndAtributo.getText());
    modelProduto.setNcm(tfNcm.getText());
    modelProduto.setValidade(tfValidade.getText());
    modelProduto.setPreco_venda(Double.parseDouble(tfVenda.getText()));
    modelProduto.setPreco_custo(Double.parseDouble(tfCusto.getText()));
    if(controllerProduto.alterarController(modelProduto)){
    JOptionPane.showMessageDialog(this, "Alterado com sucesso!!!.", "PRODUTO", 0,
    new ImageIcon(getClass().getResource("/imagem/CERTO.png"))); 
    listandoProdutos();
    tfNome.requestFocus();
    limpandoCampos();
    btnEditar.setEnabled(false);
    btnExcluir.setEnabled(false);
    btnCadastrar.setEnabled(true);
    }else{
    JOptionPane.showMessageDialog(null, "Erro!!!");
    }         
    } 
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
    try {  
    int linha = tabela.getSelectedRow();
    int cod = (int) tabela.getValueAt(linha, 0);
    if(controllerProduto.excluirController(cod)){
    JOptionPane.showMessageDialog(this, "EXCLUIDO COM SUCESSO", "PRODUTO", 0,
    new ImageIcon(getClass().getResource("/imagem/CERTO.png")));
    listandoProdutos();
    limpandoCampos(); 
    tfNome.requestFocus();
    }; 
    } catch (Exception e) {
    JOptionPane.showMessageDialog(this, "OPA!!!.", "PRODUTO", 0,
    new ImageIcon(getClass().getResource("/imagem/OPA.png"))); 
    JOptionPane.showMessageDialog(this, "INFORME UMA LINHA NA TABELA.", "PRODUTO", 0,
    new ImageIcon(getClass().getResource("/imagem/ATENCAO.png"))); 
    
    } 
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed

        
        btnCadastrar.setEnabled(true);
    btnEditar.setEnabled(false);
    btnInserir.setEnabled(false);
    btnExcluir.setEnabled(false);
        
        listandoProdutos();
    limpandoCampos();
    tfEstoque.setText("0");
    tfNome.requestFocus();
    }//GEN-LAST:event_btnAtualizarActionPerformed
 
    private void tfNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNomeKeyReleased
     tfNome.setText(tfNome.getText().toUpperCase());
    }//GEN-LAST:event_tfNomeKeyReleased

    private void tfPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPesquisaKeyReleased

    tfPesquisa.setText(tfPesquisa.getText().toUpperCase());
  
        
    }//GEN-LAST:event_tfPesquisaKeyReleased

    private void botaoInserirQuantiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoInserirQuantiaActionPerformed
    quantidade();
    }//GEN-LAST:event_botaoInserirQuantiaActionPerformed

    private void tfPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPesquisaActionPerformed
    botao = "mentira";
    DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
    final TableRowSorter<TableModel> classificador = new TableRowSorter<>(modelo);
    tabela.setRowSorter(classificador);
    String texto = tfPesquisa.getText();
    classificador.setRowFilter(RowFilter.regexFilter(texto, 1));
    }//GEN-LAST:event_tfPesquisaActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed

   
    try {
    int linha = tabela.getSelectedRow();
    int cod = (int) tabela.getValueAt(linha, 0);
    modelProduto = controllerProduto.retornarController(cod);
    tfId.setText(String.valueOf(modelProduto.getId()));
    tfNome.setText(modelProduto.getNome());
    tfBarras.setText(modelProduto.getCod_barras());
    tfEstoque.setText(modelProduto.getEstoque()+"");
    tfValidade.setText(modelProduto.getValidade());
    jcbDepartamento.setSelectedItem(modelProduto.getDepartamento());
    jcbFornecedor.setSelectedItem(modelProduto.getFornecedor());
    tfAtributo.setText(modelProduto.getAtributo());
    tfIndAtributo.setText(modelProduto.getInd_atributo());
    tfNcm.setText(modelProduto.getNcm());
     tfCusto.setText(modelProduto.getPreco_custo()+"");
    tfVenda.setText(modelProduto.getPreco_venda()+"");
    } catch (Exception e) { 
    JOptionPane.showMessageDialog(null, "SELECIONE UM PRODUTO DA TABELA!!!");
    } 
     
        
    }//GEN-LAST:event_btnInserirActionPerformed

    private void tfCustoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCustoKeyReleased
        // TODO add your handling code here: 
    }//GEN-LAST:event_tfCustoKeyReleased
    
    private void tfCustoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCustoFocusLost
    tfCusto.setText(formatador.converterPontos(tfCusto.getText()));
    }//GEN-LAST:event_tfCustoFocusLost

    private void tfVendaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfVendaFocusLost
    tfVenda.setText(formatador.converterPontos(tfVenda.getText()));
    }//GEN-LAST:event_tfVendaFocusLost

    private void tfBuscaPorCodBarrasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfBuscaPorCodBarrasKeyReleased
       trazerProdutoPeloCod(evt);
    }//GEN-LAST:event_tfBuscaPorCodBarrasKeyReleased

    private void tfPesquisaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPesquisaFocusLost
     
    }//GEN-LAST:event_tfPesquisaFocusLost

    private void tfBuscaPorCodBarrasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfBuscaPorCodBarrasFocusLost
//    listandoProdutos();
    }//GEN-LAST:event_tfBuscaPorCodBarrasFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    DefaultTableModel modelo = (DefaultTableModel) tabela.getModel(); 
    final TableRowSorter<TableModel> classificador = new TableRowSorter<>(modelo);
    tabela.setRowSorter(classificador);
    String texto = tfPesquisa.getText();  
    classificador.setRowFilter(RowFilter.regexFilter(texto, 1));
    
    }//GEN-LAST:event_jButton1ActionPerformed
   
  
    private void trazerProdutoPeloCod(java.awt.event.KeyEvent e){
        
         DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();   
           
        if(e.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){      
        modelo.setNumRows(0);
         modelProduto = new ModelProduto();    
                 
        modelProduto = controllerProduto.retornarCodigoBarrasController(tfBuscaPorCodBarras.getText());
   
        modelo.addRow(new Object[]{
        
        modelProduto.getId(),   
        modelProduto.getNome(), 
        modelProduto.getEstoque(), 
        modelProduto.getCod_barras(),   
        modelProduto.getDepartamento(), 
        modelProduto.getAtributo(),
        
        modelProduto.getInd_atributo(),   
        modelProduto.getNcm(), 
        modelProduto.getFornecedor(), 
        
        modelProduto.getValidade(),   
        modelProduto.getPreco_custo(), 
        modelProduto.getPreco_venda()
       
        
        });
        tfBuscaPorCodBarras.setText("");
    }
    
    }
    private void quantidade(){
    
        try {  
            
        
String quantidade = JOptionPane.showInputDialog("INFORME A QUANTIDADE DESSE PRODUTO");
    String estoque= tfEstoque.getText();
    int soma; 
    soma = Integer.parseInt(quantidade) + Integer.parseInt(estoque);
    tfEstoque.setText(soma+"");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Informe somente números!");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewProduto2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewProduto2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewProduto2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewProduto2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewProduto2().setVisible(true);
            }
        });
    }
    
      
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoInserirQuantia;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbDepartamento;
    private javax.swing.JComboBox<String> jcbFornecedor;
    public static javax.swing.JTable tabela;
    private javax.swing.JTextField tfAtributo;
    private javax.swing.JTextField tfBarras;
    private javax.swing.JTextField tfBuscaPorCodBarras;
    private javax.swing.JTextField tfCusto;
    private javax.swing.JTextField tfEstoque;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfIndAtributo;
    private javax.swing.JTextField tfNcm;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfPesquisa;
    private javax.swing.JTextField tfValidade;
    private javax.swing.JTextField tfVenda;
    // End of variables declaration//GEN-END:variables
   
 public void corLinha(){    
     tabela.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
            boolean isSelected, boolean hasFocus, int row, int column) {
                super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                //A coluna do status é 3 
                int ref = Integer.parseInt(String.valueOf(table.getValueAt(row, 2)));//Coluna Status
                //Coloca cor em todas as linhas,COLUNA(3) que tem o valor "Aberto"
                if (ref < 5) {//Se Status for igual a "Aberto"
                    setBackground(new Color(237, 171, 168));//Preenche a linha de vermelho
                    setForeground(Color.WHITE);//E a fonte de branco
                } else { 
                    boolean sel = isSelected;
                    if (sel == true) {
                        setBackground(getBackground());
                        setForeground(getForeground());
                    } else {//Se Status não for "Aberto" 
                        setBackground(Color.WHITE);//Preenche a linha de branco
                        setForeground(new Color(51, 51, 51));//E a fonte de preto
                    } 
                }
                return this;
            }
       
     });
 
}
 
 
 private void setIcon() {
setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagem/comp.png"))); 
    }
}