/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerUsuario;
import Model.ModelUsuario;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.PlainDocument;

/**
 *
 * @author Monet
 */ 
public class ViewUsuario extends javax.swing.JFrame {
    ModelUsuario modelUsuario = new ModelUsuario();
    ArrayList<ModelUsuario> listaModelUsuario = new ArrayList<>();
    ControllerUsuario controllerUsuario = new ControllerUsuario();
            /**
     * Creates new form ViewUsuario
     */
    public ViewUsuario() { 
        initComponents(); 
        setIcon();
        listando();
        tfSenha.setDocument(new Documento2());
    }
    private void listando(){
    listaModelUsuario = controllerUsuario.listaModelUsuarioController();
    DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
    modelo.setNumRows(0);
    int cont = listaModelUsuario.size();
    for(int i = 0 ; i < cont; i++){
    modelo.addRow(new Object[]{
    listaModelUsuario.get(i).getId(),
    listaModelUsuario.get(i).getNome(),
    listaModelUsuario.get(i).getSenha(), 
    listaModelUsuario.get(i).getTipo()
    });
    }
    }
    private void limparCampos(){
    tfId.setText("");
    tfNome.setText("");
    tfSenha.setText("");
    jComboBox1.setSelectedItem("TIPO");
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */ 
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        tfId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfSenha = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        butaocadastro = new javax.swing.JButton();
        butaoEditar = new javax.swing.JButton();
        butaExcluir = new javax.swing.JButton();
        butaocadastro3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("USUARIO"); // NOI18N
        setResizable(false);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "NOME", "SENHA", "TIPO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);
        if (tabela.getColumnModel().getColumnCount() > 0) {
            tabela.getColumnModel().getColumn(0).setResizable(false);
            tabela.getColumnModel().getColumn(0).setPreferredWidth(40);
            tabela.getColumnModel().getColumn(1).setResizable(false);
            tabela.getColumnModel().getColumn(1).setPreferredWidth(200);
            tabela.getColumnModel().getColumn(2).setResizable(false);
            tabela.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel1.setText("ID:");

        tfId.setEditable(false);

        jLabel2.setText("NOME:");

        tfNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfNomeKeyReleased(evt);
            }
        });

        jLabel3.setText("SENHA:");

        jLabel4.setText("TIPO:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMINISTRADOR", "ESTOQUE", "VENDEDOR", " " }));

        butaocadastro.setText("CADASTRAR");
        butaocadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butaocadastroActionPerformed(evt);
            }
        });

        butaoEditar.setText("EDITAR");
        butaoEditar.setEnabled(false);
        butaoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butaoEditarActionPerformed(evt);
            }
        });

        butaExcluir.setText("EXCLUIR");
        butaExcluir.setEnabled(false);
        butaExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butaExcluirActionPerformed(evt);
            }
        });

        butaocadastro3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Atualizar.png"))); // NOI18N
        butaocadastro3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butaocadastro3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(butaocadastro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butaoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butaExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butaocadastro3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(tfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butaocadastro)
                    .addComponent(butaoEditar)
                    .addComponent(butaExcluir)
                    .addComponent(butaocadastro3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butaocadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butaocadastroActionPerformed
    if(tfNome.getText().equals("") || tfSenha.getText().equals("") || jComboBox1.getSelectedItem().equals("TIPO")){
    JOptionPane.showMessageDialog(this, "OPA!!!.", "USUARIO", 0,
    new ImageIcon(getClass().getResource("/imagem/OPA.png"))); 
    JOptionPane.showMessageDialog(this, "Todos os campos são obrigatórios!!!.", "USUARIO", 0,
    new ImageIcon(getClass().getResource("/imagem/ATENCAO.png"))); 
    JOptionPane.showMessageDialog(this, "NÃO IDENTIFIQUEI OS DADOS!!!.", "USUARIO", 0,
    new ImageIcon(getClass().getResource("/imagem/INFORME USUARIO.png"))); 
    }else{
    modelUsuario.setNome(tfNome.getText());
    modelUsuario.setSenha(tfSenha.getText());
    modelUsuario.setTipo(jComboBox1.getSelectedItem()+"");
    if(controllerUsuario.salvarUsuarioController(modelUsuario)>0){
      
    JOptionPane.showMessageDialog(this, "Salvo com sucesso!!!", "USUARIO", 0,
    new ImageIcon(getClass().getResource("/imagem/CERTO.png"))); 
    listando();   
    limparCampos();   
    } 
    }
    }//GEN-LAST:event_butaocadastroActionPerformed

    private void butaoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butaoEditarActionPerformed

    if(tfId.getText().equals("")){
    JOptionPane.showMessageDialog(this, "OPA!!!.", "USUARIO", 0,
    new ImageIcon(getClass().getResource("/imagem/OPA.png"))); 
    JOptionPane.showMessageDialog(this, "INFORME UMA LINHA NA TABELA.", "USUARIO", 0,
    new ImageIcon(getClass().getResource("/imagem/ATENCAO.png"))); 
    JOptionPane.showMessageDialog(this, "USUARIO NÃO SELECIONADO!.", "USUARIO", 0,
    new ImageIcon(getClass().getResource("/imagem/ERRO USUARIO.png"))); 
    }else{
        
    
    modelUsuario.setNome(tfNome.getText());
    modelUsuario.setSenha(tfSenha.getText());
    modelUsuario.setTipo(jComboBox1.getSelectedItem()+"");
    if(controllerUsuario.alterarUsuarioController(modelUsuario)){
      JOptionPane.showMessageDialog(this, "Alterado com sucesso!!!.", "USUARIO", 0,
    new ImageIcon(getClass().getResource("/imagem/CERTO.png"))); 
    listando();
    limparCampos();
    }else{
    JOptionPane.showMessageDialog(null, "Erro!!!");
    }         
    }
    }//GEN-LAST:event_butaoEditarActionPerformed

    private void butaExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butaExcluirActionPerformed
    try {  
    int linha = tabela.getSelectedRow();
    int cod = (int) tabela.getValueAt(linha, 0);
    if(controllerUsuario.excluirUsuarioController(cod)){
    JOptionPane.showMessageDialog(null, "Excluído com sucesso!!!");
    listando();
    limparCampos();
    };
    } catch (Exception e) {
    JOptionPane.showMessageDialog(this, "OPA!!!.", "USUARIO", 0,
    new ImageIcon(getClass().getResource("/imagem/OPA.png"))); 
    JOptionPane.showMessageDialog(this, "INFORME UMA LINHA NA TABELA.", "USUARIO", 0,
    new ImageIcon(getClass().getResource("/imagem/ATENCAO.png"))); 
    JOptionPane.showMessageDialog(this, "USUARIO NÃO SELECIONADO!.", "USUARIO", 0,
    new ImageIcon(getClass().getResource("/imagem/ERRO USUARIO.png")));
    }
    }//GEN-LAST:event_butaExcluirActionPerformed

    private void butaocadastro3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butaocadastro3ActionPerformed
    butaocadastro.setEnabled(true);
    butaoEditar.setEnabled(false);
    butaExcluir.setEnabled(false); 
    limparCampos(); 
    listando();
    }//GEN-LAST:event_butaocadastro3ActionPerformed
 
    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
    butaocadastro.setEnabled(false);
    butaoEditar.setEnabled(true);
    butaExcluir.setEnabled(true);
    
    
    int linha = tabela.getSelectedRow();
    int cod = (int) tabela.getValueAt(linha, 0);
    try {
    modelUsuario = controllerUsuario.retornarUsuarioController(cod);
    tfId.setText(String.valueOf(modelUsuario.getId()));
    tfNome.setText(modelUsuario.getNome());
    tfSenha.setText(modelUsuario.getSenha());
    jComboBox1.setSelectedItem(modelUsuario.getTipo());
    } catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Erro!!!");
    }      
    }//GEN-LAST:event_tabelaMouseClicked

    private void tfNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNomeKeyReleased
    tfNome.setText(tfNome.getText().toUpperCase());

    }//GEN-LAST:event_tfNomeKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butaExcluir;
    private javax.swing.JButton butaoEditar;
    private javax.swing.JButton butaocadastro;
    private javax.swing.JButton butaocadastro3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfSenha;
    // End of variables declaration//GEN-END:variables

private void setIcon() {
setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagem/comp.png"))); 
    }

}


  class Documento2 extends PlainDocument{  
    
    @Override
    public void insertString(int offs, String str, AttributeSet a) throws BadLocationException {
        try {
            
         
        int tam = (this.getLength() + str.length());
     if(tam <=4){
     super.insertString(offs, str.replaceAll("[aA-zZ]", ""), a);     
     }else{
     super.insertString(offs, str.replaceAll("{1-9}", ""), a);
     }
       } catch (Exception e) {
        } 
    }





}