/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


import Controller.ControllerTipoContas;
import Model.ModelTipoContas;
import java.awt.Toolkit;
import java.util.ArrayList; 
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
 
/**
 *
 * @author Monet
 */
public class ViewTipoContas extends javax.swing.JFrame {
    ModelTipoContas mod = new ModelTipoContas();
   
    ArrayList<ModelTipoContas> lista = new ArrayList<>();
    ControllerTipoContas controller = new ControllerTipoContas();

    /**
     * Creates new form ViewCidade
     */
    public ViewTipoContas() {
        initComponents();
        setIcon();
        listando();
    }
    private void limparCampos(){
    tfCidade.setText("");
    tfId.setText("");
    }
     private void listando(){ 
    lista = controller.listaModelController();
    DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
    modelo.setNumRows(0);
    int cont = lista.size();
    for(int i = 0; i <cont; i++){
    modelo.addRow(new Object[]{
    lista.get(i).getId(),
    lista.get(i).getNome()
    

    });
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        tfId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfCidade = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "NOME"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);
        if (tabela.getColumnModel().getColumnCount() > 0) {
            tabela.getColumnModel().getColumn(0).setResizable(false);
            tabela.getColumnModel().getColumn(0).setPreferredWidth(40);
            tabela.getColumnModel().getColumn(1).setResizable(false);
            tabela.getColumnModel().getColumn(1).setPreferredWidth(250);
        }

        jLabel1.setText("ID:");

        tfId.setEditable(false);

        jLabel2.setText("NOME:");

        tfCidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfCidadeKeyReleased(evt);
            }
        });

        jButton1.setText("EDITAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("EXCLUIR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("CADASTRAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCidade))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(tfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     if(tfCidade.getText().equals("")){
    JOptionPane.showMessageDialog(this, "OPA!!!.", "CIDADE", 0,
    new ImageIcon(getClass().getResource("/imagem/OPA.png"))); 
    JOptionPane.showMessageDialog(this, "Todos os campos são obrigatórios!!!.", "CIDADE", 0,
    new ImageIcon(getClass().getResource("/imagem/ATENCAO.png"))); 
    }else{
    mod.setNome(tfCidade.getText()); 
    if(controller.salvarController(mod)>0){
    JOptionPane.showMessageDialog(this, "Salvo com sucesso!!!.", "CIDADE", 0,
    new ImageIcon(getClass().getResource("/imagem/CERTO.png"))); 
    listando();   
    limparCampos();   
    } 
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tfCidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCidadeKeyReleased
      tfCidade.setText(tfCidade.getText().toUpperCase());
    }//GEN-LAST:event_tfCidadeKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    try {  
    int linha = tabela.getSelectedRow();
    int cod = (int) tabela.getValueAt(linha, 0);
    if(controller.excluirController(cod)){
    JOptionPane.showMessageDialog(this, "EXCLUIDO COM SUCESSO", "CIDADE", 0,
    new ImageIcon(getClass().getResource("/imagem/CERTO.png")));
    listando();
    limparCampos();
    };
    } catch (Exception e) {
    JOptionPane.showMessageDialog(this, "OPA!!!.", "CIDADE", 0,
    new ImageIcon(getClass().getResource("/imagem/OPA.png"))); 
    JOptionPane.showMessageDialog(this, "INFORME UMA LINHA NA TABELA.", "CIDADE", 0,
    new ImageIcon(getClass().getResource("/imagem/ATENCAO.png"))); 
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    if(tfId.getText().equals("")){
    JOptionPane.showMessageDialog(this, "OPA!!!.", "CIDADE", 0,
    new ImageIcon(getClass().getResource("/imagem/OPA.png"))); 
    JOptionPane.showMessageDialog(this, "INFORME UMA LINHA NA TABELA.", "CIDADE", 0,
    new ImageIcon(getClass().getResource("/imagem/ATENCAO.png"))); 
   
    }else{
         
    mod.setNome(tfCidade.getText());

    if(controller.alterarController(mod)){
    JOptionPane.showMessageDialog(this, "Alterado com sucesso!!!.", "CIDADE", 0,
    new ImageIcon(getClass().getResource("/imagem/CERTO.png"))); 
    listando();
    limparCampos();
    }else{
    JOptionPane.showMessageDialog(null, "Erro!!!");
    }         
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
    int linha = tabela.getSelectedRow();
    int cod = (int) tabela.getValueAt(linha, 0); 
    try {
    mod = controller.retornarController(cod);
    tfId.setText(String.valueOf(mod.getId()));
    tfCidade.setText(mod.getNome());
    } catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Erro!!!");
    }      
    }//GEN-LAST:event_tabelaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewTipoContas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewTipoContas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewTipoContas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewTipoContas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewTipoContas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField tfCidade;
    private javax.swing.JTextField tfId;
    // End of variables declaration//GEN-END:variables


private void setIcon() {
setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagem/comp.png"))); 
    }

}
