/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View; 

import Controller.ControllerBairro;
import Controller.ControllerCidade;
import Controller.ControllerCliente;
import Controller.ControllerRua;
import Model.ModelBairro;
import Model.ModelCidade;
import Model.ModelCliente;
import Model.ModelRua;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.ImageIcon; 
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Monet 
 */
public class ViewCliente extends javax.swing.JFrame {
    ArrayList<ModelCliente> lista = new ArrayList<>();
    ModelCliente mod = new ModelCliente();
    ControllerCliente controller = new ControllerCliente();
    
    ModelBairro modelBairro = new ModelBairro();
    ControllerBairro controllerBairro = new ControllerBairro();
    ArrayList<ModelBairro> listaBairro = new ArrayList<>();
    
    ModelCidade modelCidade = new ModelCidade();
    ControllerCidade controllerCidade = new ControllerCidade();
    ArrayList<ModelCidade> listaCidade = new ArrayList<>();
    
    ModelRua modelRua = new ModelRua();
    ControllerRua controllerRua = new ControllerRua();
    ArrayList<ModelRua> listaRua = new ArrayList<>();
    /**
     * Creates new form ViewCliente 
     */
    public ViewCliente() {
        initComponents();
        listando();
        listandoCidades();
        listandoBairros();
        listandoRuas();
        setIcon();
    }
    private void limparCampos(){
    tfId.setText("");
    tfNascimento.setText(""); 
    tfNome.setText("");
    tfNumeroDaCasa.setText("");
    tfRg.setText("");
    tfTelefone.setText("");
    jcbBairro.setSelectedItem("BAIRRO");
    jcbCidade.setSelectedItem("CIDADE");
    jcbRua.setSelectedItem("RUA");

    }
    
    private void listandoRuas(){
    listaRua = controllerRua.listaModelController();
    jcbRua.removeAllItems();
        for (int i = 0; i < listaRua.size(); i++) {
        jcbRua.addItem(listaRua.get(i).getNome());
        }
    }
    private void listandoCidades(){
    listaCidade = controllerCidade.listaModelController();
    jcbCidade.removeAllItems();
        for (int i = 0; i < listaCidade.size(); i++) {
        jcbCidade.addItem(listaCidade.get(i).getNome());
        }
    }
    private void listandoBairros(){
    listaBairro = controllerBairro.listaModelController();
    jcbBairro.removeAllItems();
    for (int i = 0; i < listaBairro.size(); i++) {
    jcbBairro.addItem(listaBairro.get(i).getNome());
        }
    }
    private void listando(){  
    lista = controller.listaModelUsuarioController();
    DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
    modelo.setNumRows(0);
    int cont = lista.size();
    for(int i = 0; i <cont; i++){
    modelo.addRow(new Object[]{
    lista.get(i).getId(),
    lista.get(i).getNome(),
    lista.get(i).getNascimento(),
    lista.get(i).getBairro(),
    lista.get(i).getRua(),
    lista.get(i).getNumero_casa(),
    lista.get(i).getCidade(),
    lista.get(i).getRg(),
    lista.get(i).getTelefone()

    });
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        tfId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfNascimento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jcbBairro = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jcbRua = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        tfNumeroDaCasa = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jcbCidade = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        tfRg = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfTelefone = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        tfPesquisar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CADASTRAR CLIENTES");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tabela.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NOME", "NASC.", "BAIRRO", "RUA", "Nº", "CIDADE", "RG", "FONE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);
        if (tabela.getColumnModel().getColumnCount() > 0) {
            tabela.getColumnModel().getColumn(0).setResizable(false);
            tabela.getColumnModel().getColumn(1).setResizable(false);
            tabela.getColumnModel().getColumn(1).setPreferredWidth(200);
            tabela.getColumnModel().getColumn(2).setResizable(false);
            tabela.getColumnModel().getColumn(3).setResizable(false);
            tabela.getColumnModel().getColumn(4).setResizable(false);
            tabela.getColumnModel().getColumn(5).setResizable(false);
            tabela.getColumnModel().getColumn(6).setResizable(false);
            tabela.getColumnModel().getColumn(7).setResizable(false);
            tabela.getColumnModel().getColumn(8).setResizable(false);
        }

        jLabel1.setText("ID:");

        jLabel2.setText("NOME:");

        tfNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfNomeKeyReleased(evt);
            }
        });

        jLabel3.setText("NASCIMENTO:");

        tfNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNascimentoActionPerformed(evt);
            }
        });

        jLabel4.setText("BAIRRO:");

        jcbBairro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("RUA:");

        jcbRua.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("NUMERO:");

        jLabel7.setText("CIDADE:");

        jcbCidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setText("CPF:");

        jLabel9.setText("TELEFONE:");

        jButton1.setText("CADASTRAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("EXCLUIR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("EDITAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        tfPesquisar.setEditable(false);
        tfPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfPesquisarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 703, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbRua, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfNascimento)
                            .addComponent(tfNumeroDaCasa, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbBairro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbCidade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfRg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tfPesquisar))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(tfNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jcbBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jcbRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(tfNumeroDaCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(jcbCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(tfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNascimentoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    if(tfNome.getText().equals("") || tfNascimento.getText().equals("") 
    || jcbBairro.getSelectedItem().equals("BAIRRO") || jcbCidade.getSelectedItem().equals("CIDADE") 
    || jcbRua.getSelectedItem().equals("RUA") || tfNumeroDaCasa.getText().equals("") 
    || tfRg.getText().equals("")  || tfTelefone.getText().equals("")){
    JOptionPane.showMessageDialog(this, "OPA!!!.", "CLIENTE", 0,
    new ImageIcon(getClass().getResource("/imagem/OPA.png"))); 
    JOptionPane.showMessageDialog(this, "Todos os campos são obrigatórios!!!.", "CLIENTE", 0,
    new ImageIcon(getClass().getResource("/imagem/ATENCAO.png"))); 
    JOptionPane.showMessageDialog(this, "NÃO IDENTIFIQUEI OS DADOS!.", "CLIENTE", 0,
    new ImageIcon(getClass().getResource("/imagem/INFORME USUARIO.png")));
    }else{
    mod.setNome(tfNome.getText()); 
    mod.setNascimento(tfNascimento.getText());
    mod.setBairro(jcbBairro.getSelectedItem()+"");
    mod.setCidade(jcbCidade.getSelectedItem()+"");
    mod.setRua(jcbRua.getSelectedItem()+"");
    mod.setNumero_casa(tfNumeroDaCasa.getText());
    mod.setRg(tfRg.getText());
    mod.setTelefone(tfTelefone.getText());
    if(controller.salvarController(mod)>0){
    JOptionPane.showMessageDialog(this, "Salvo com sucesso!!!.", "CLIENTE", 0,
    new ImageIcon(getClass().getResource("/imagem/CERTO.png"))); 
    listando();   
    limparCampos();   
    } 
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     try {  
    int linha = tabela.getSelectedRow();
    int cod = (int) tabela.getValueAt(linha, 0);
    if(controller.excluirController(cod)){
    JOptionPane.showMessageDialog(this, "EXCLUIDO COM SUCESSO", "CLIENTE", 0,
    new ImageIcon(getClass().getResource("/imagem/CERTO.png")));
    listando();
    limparCampos();
    };
    } catch (Exception e) {
    JOptionPane.showMessageDialog(this, "OPA!!!.", "CLIENTE", 0,
    new ImageIcon(getClass().getResource("/imagem/OPA.png"))); 
    JOptionPane.showMessageDialog(this, "INFORME UMA LINHA NA TABELA.", "CLIENTE", 0,
    new ImageIcon(getClass().getResource("/imagem/ATENCAO.png"))); 
    JOptionPane.showMessageDialog(this, "CLIENTE NÃO SELECIONADO!.", "CLIENTE", 0,
    new ImageIcon(getClass().getResource("/imagem/ERRO USUARIO.png"))); 
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
    int linha = tabela.getSelectedRow();
    int cod = (int) tabela.getValueAt(linha, 0); 
    try {
    mod = controller.retornarController(cod);
    tfId.setText(String.valueOf(mod.getId()));
    tfNome.setText(mod.getNome());
    tfNascimento.setText(mod.getNascimento());
    tfRg.setText(mod.getRg());
    tfTelefone.setText(mod.getTelefone());
    jcbBairro.setSelectedItem(mod.getBairro());
    jcbCidade.setSelectedItem(mod.getCidade());
    jcbRua.setSelectedItem(mod.getRua());
    tfNumeroDaCasa.setText(mod.getNumero_casa());
    } catch (Exception e) { 
    JOptionPane.showMessageDialog(null, "Erro!!!");
    }      
    }//GEN-LAST:event_tabelaMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    if(tfNome.getText().equals("") || tfNascimento.getText().equals("") 
    || jcbBairro.getSelectedItem().equals("BAIRRO") || jcbCidade.getSelectedItem().equals("CIDADE") 
    || jcbRua.getSelectedItem().equals("RUA") || tfNumeroDaCasa.getText().equals("") 
    || tfRg.getText().equals("")  || tfTelefone.getText().equals("")){
    JOptionPane.showMessageDialog(this, "OPA!!!.", "CLIENTE", 0,
    new ImageIcon(getClass().getResource("/imagem/OPA.png"))); 
    JOptionPane.showMessageDialog(this, "Todos os campos são obrigatórios!!!.", "CLIENTE", 0,
    new ImageIcon(getClass().getResource("/imagem/ATENCAO.png"))); 
    JOptionPane.showMessageDialog(this, "NÃO IDENTIFIQUEI OS DADOS!.", "CLIENTE", 0,
    new ImageIcon(getClass().getResource("/imagem/INFORME USUARIO.png")));
    }else{
        
    mod.setNome(tfNome.getText());
    mod.setNascimento(tfNascimento.getText());
    mod.setNumero_casa(tfNumeroDaCasa.getText());
    mod.setRg(tfRg.getText());
    mod.setTelefone(tfTelefone.getText());
    mod.setBairro(String.valueOf(jcbBairro.getSelectedItem()));
    mod.setCidade(String.valueOf(jcbCidade.getSelectedItem()));
    mod.setRua(String.valueOf(jcbRua.getSelectedItem()));
    controller.alterarController(mod);
    listando(); 
    JOptionPane.showMessageDialog(this, "Alterado com sucesso!!!.", "CLIENTE", 0,
    new ImageIcon(getClass().getResource("/imagem/CERTO.png"))); 
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tfNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNomeKeyReleased
    tfNome.setText(tfNome.getText().toUpperCase());

    }//GEN-LAST:event_tfNomeKeyReleased

    private void tfPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPesquisarKeyReleased
    tfPesquisar.setText(tfPesquisar.getText().toUpperCase());
     ModelCliente.listarCat(tfPesquisar.getText());
    }//GEN-LAST:event_tfPesquisarKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbBairro;
    private javax.swing.JComboBox<String> jcbCidade;
    private javax.swing.JComboBox<String> jcbRua;
    public static javax.swing.JTable tabela;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfNascimento;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfNumeroDaCasa;
    private javax.swing.JTextField tfPesquisar;
    private javax.swing.JTextField tfRg;
    private javax.swing.JTextField tfTelefone;
    // End of variables declaration//GEN-END:variables

private void setIcon() {
setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagem/comp.png"))); 
    }
}
